// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o perfil do usu\xE1rio autenticado (nome, status e dados b\xE1sicos de contato).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("nome_completo, status, celular, cidade, estado").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const perfil = { email: ctx.getUserEmail(), ...data ?? {} };
    return {
      content: [{ type: "text", text: JSON.stringify(perfil, null, 2) }],
      structuredContent: { perfil }
    };
  }
});

// src/lib/mcp/tools/minhas-notificacoes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var minhas_notificacoes_default = defineTool2({
  name: "minhas_notificacoes",
  title: "Minhas notifica\xE7\xF5es",
  description: "Lista os avisos internos mais recentes do usu\xE1rio autenticado. Opcionalmente filtra apenas os n\xE3o lidos.",
  inputSchema: {
    apenas_nao_lidos: z.boolean().default(false).describe("Se true, retorna apenas avisos ainda n\xE3o lidos."),
    limite: z.number().int().min(1).max(50).default(10).describe("Quantidade m\xE1xima de avisos a retornar (1 a 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ apenas_nao_lidos, limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("avisos_internos").select("id, tipo, titulo, mensagem, lido, link, created_at").order("created_at", { ascending: false }).limit(limite);
    if (apenas_nao_lidos) query = query.eq("lido", false);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const avisos = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: avisos.length ? JSON.stringify(avisos, null, 2) : "Nenhum aviso encontrado."
        }
      ],
      structuredContent: { avisos }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wfgorvzzlbvzajzwxxzc";
var mcp_default = defineMcp({
  name: "fer-mcp",
  title: "FER \u2014 Gest\xE3o de Tratamentos MCP",
  version: "0.1.0",
  instructions: "Ferramentas da plataforma FER de gest\xE3o de tratamentos. Use `whoami` para confirmar quem \xE9 o usu\xE1rio conectado e `minhas_notificacoes` para consultar avisos internos. Todas as ferramentas operam apenas sobre os dados do pr\xF3prio usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, minhas_notificacoes_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
